export type CatalogType = "planet" | "star" | "galaxy" | "moon" | "black hole" | "nebula";

export interface CatalogEntry {
  id: string;
  name: string;
  type: CatalogType;
  distance: string;
  summary: string;
  facts: { label: string; value: string }[];
  palette: [string, string, string];
  rings?: boolean;
}

export const CATALOG: CatalogEntry[] = [
  { id: "mercury", name: "Mercury", type: "planet", distance: "0.39 AU from Sun", summary: "The smallest planet and closest to the Sun, with extreme temperature swings and a heavily cratered surface.", facts: [{ label: "Radius", value: "2,440 km" }, { label: "Mass", value: "0.055 Earths" }, { label: "Day length", value: "176 Earth days (solar)" }, { label: "Year", value: "88 days" }, { label: "Surface temp", value: "−173 to 427 °C" }, { label: "Moons", value: "0" }], palette: ["#3d3a38", "#8a837c", "#c9c2b8"] },
  { id: "venus", name: "Venus", type: "planet", distance: "0.72 AU from Sun", summary: "A runaway greenhouse world hidden under sulfuric acid clouds — the hottest planet in the Solar System.", facts: [{ label: "Radius", value: "6,052 km" }, { label: "Mass", value: "0.815 Earths" }, { label: "Surface pressure", value: "92 bar" }, { label: "Surface temp", value: "464 °C" }, { label: "Rotation", value: "243 days, retrograde" }, { label: "Moons", value: "0" }], palette: ["#7a4a1a", "#d9a35b", "#f3dcab"] },
  { id: "earth", name: "Earth", type: "planet", distance: "1 AU from Sun", summary: "The only known world with life, liquid surface oceans and active plate tectonics.", facts: [{ label: "Radius", value: "6,371 km" }, { label: "Mass", value: "5.97 × 10²⁴ kg" }, { label: "Gravity", value: "9.81 m/s²" }, { label: "Year", value: "365.25 days" }, { label: "Atmosphere", value: "78% N₂, 21% O₂" }, { label: "Moons", value: "1" }], palette: ["#0b2a5b", "#2f7fd1", "#a9e2c4"] },
  { id: "mars", name: "Mars", type: "planet", distance: "1.52 AU from Sun", summary: "The red planet, home to Olympus Mons and Valles Marineris, with evidence of ancient water.", facts: [{ label: "Radius", value: "3,390 km" }, { label: "Mass", value: "0.107 Earths" }, { label: "Gravity", value: "3.72 m/s²" }, { label: "Day", value: "24.6 h" }, { label: "Year", value: "687 days" }, { label: "Moons", value: "2 (Phobos, Deimos)" }], palette: ["#4a1a0e", "#b5502b", "#e8a072"] },
  { id: "jupiter", name: "Jupiter", type: "planet", distance: "5.2 AU from Sun", summary: "The largest planet, a gas giant with a storm — the Great Red Spot — larger than Earth.", facts: [{ label: "Radius", value: "69,911 km" }, { label: "Mass", value: "318 Earths" }, { label: "Day", value: "9.9 h" }, { label: "Year", value: "11.9 years" }, { label: "Composition", value: "H₂, He" }, { label: "Moons", value: "95 known" }], palette: ["#5a3b25", "#c79b6d", "#efe1c8"] },
  { id: "saturn", name: "Saturn", type: "planet", distance: "9.5 AU from Sun", summary: "Famous for its brilliant ring system of ice and rock; less dense than water.", facts: [{ label: "Radius", value: "58,232 km" }, { label: "Mass", value: "95 Earths" }, { label: "Density", value: "0.69 g/cm³" }, { label: "Year", value: "29.4 years" }, { label: "Ring span", value: "~282,000 km" }, { label: "Moons", value: "146 known" }], palette: ["#6b5530", "#d6b97c", "#f6e8c3"], rings: true },
  { id: "uranus", name: "Uranus", type: "planet", distance: "19.2 AU from Sun", summary: "An ice giant tilted 98°, rolling around the Sun on its side.", facts: [{ label: "Radius", value: "25,362 km" }, { label: "Mass", value: "14.5 Earths" }, { label: "Axial tilt", value: "97.8°" }, { label: "Year", value: "84 years" }, { label: "Min temp", value: "−224 °C" }, { label: "Moons", value: "28" }], palette: ["#1f5a66", "#6fc6d1", "#c9f1f2"], rings: true },
  { id: "neptune", name: "Neptune", type: "planet", distance: "30.1 AU from Sun", summary: "The windiest planet, with supersonic storms reaching 2,100 km/h.", facts: [{ label: "Radius", value: "24,622 km" }, { label: "Mass", value: "17.1 Earths" }, { label: "Wind speed", value: "2,100 km/h" }, { label: "Year", value: "165 years" }, { label: "Discovered", value: "1846, by math" }, { label: "Moons", value: "16" }], palette: ["#0c1f6b", "#3359d6", "#8fb3ff"] },
  { id: "proxima-b", name: "Proxima Centauri b", type: "planet", distance: "4.24 ly", summary: "The closest known exoplanet, orbiting within its red dwarf's habitable zone.", facts: [{ label: "Min mass", value: "1.07 Earths" }, { label: "Orbital period", value: "11.2 days" }, { label: "Orbit", value: "0.049 AU" }, { label: "Host", value: "M5.5V red dwarf" }, { label: "Discovered", value: "2016" }, { label: "Eq. temp", value: "~234 K" }], palette: ["#3b1a2e", "#9a4f6a", "#e0a6a6"] },
  { id: "trappist-1e", name: "TRAPPIST-1e", type: "planet", distance: "40.7 ly", summary: "A rocky, Earth-sized world in the TRAPPIST-1 system — among the most promising for habitability.", facts: [{ label: "Radius", value: "0.92 Earths" }, { label: "Mass", value: "0.69 Earths" }, { label: "Period", value: "6.1 days" }, { label: "System", value: "7 rocky planets" }, { label: "Eq. temp", value: "~250 K" }, { label: "Discovered", value: "2017" }], palette: ["#142a3a", "#3f7f8f", "#b6dbd2"] },
  { id: "moon", name: "The Moon", type: "moon", distance: "384,400 km from Earth", summary: "Earth's only natural satellite, likely formed from a giant impact 4.5 billion years ago.", facts: [{ label: "Radius", value: "1,737 km" }, { label: "Gravity", value: "1.62 m/s²" }, { label: "Orbit", value: "27.3 days" }, { label: "Recession", value: "3.8 cm/year" }, { label: "Humans walked", value: "12" }, { label: "Tidally locked", value: "Yes" }], palette: ["#3a3a3e", "#8d8d92", "#d6d6d9"] },
  { id: "europa", name: "Europa", type: "moon", distance: "Orbits Jupiter", summary: "An icy moon of Jupiter hiding a global saltwater ocean beneath its crust.", facts: [{ label: "Radius", value: "1,561 km" }, { label: "Ice shell", value: "15–25 km" }, { label: "Ocean depth", value: "~100 km" }, { label: "Orbit", value: "3.55 days" }, { label: "Missions", value: "Europa Clipper" }, { label: "Surface temp", value: "−160 °C" }], palette: ["#5b4630", "#c4ab86", "#f2e8d8"] },
  { id: "titan", name: "Titan", type: "moon", distance: "Orbits Saturn", summary: "Saturn's largest moon, with a thick nitrogen atmosphere and lakes of liquid methane.", facts: [{ label: "Radius", value: "2,575 km" }, { label: "Surface pressure", value: "1.45 bar" }, { label: "Surface temp", value: "−179 °C" }, { label: "Lakes", value: "Methane/ethane" }, { label: "Orbit", value: "15.9 days" }, { label: "Mission", value: "Dragonfly (2028)" }], palette: ["#5a3a10", "#c98a2e", "#f0c878"] },
  { id: "enceladus", name: "Enceladus", type: "moon", distance: "Orbits Saturn", summary: "A small moon spraying water geysers from its south pole into space.", facts: [{ label: "Radius", value: "252 km" }, { label: "Albedo", value: "~0.99" }, { label: "Plumes", value: "Water + organics" }, { label: "Orbit", value: "1.37 days" }, { label: "Ocean", value: "Global, subsurface" }, { label: "Feeds", value: "Saturn's E ring" }], palette: ["#6d8090", "#c9d9e6", "#ffffff"] },
  { id: "io", name: "Io", type: "moon", distance: "Orbits Jupiter", summary: "The most volcanically active body in the Solar System, heated by tidal flexing.", facts: [{ label: "Radius", value: "1,822 km" }, { label: "Active volcanoes", value: "400+" }, { label: "Orbit", value: "1.77 days" }, { label: "Surface", value: "Sulfur compounds" }, { label: "Heating", value: "Tidal" }, { label: "Plume height", value: "up to 500 km" }], palette: ["#6b5a10", "#d6b83a", "#f6ec9c"] },
  { id: "sun", name: "The Sun", type: "star", distance: "1 AU", summary: "A G2V main-sequence star, 4.6 billion years old, fusing 600 million tonnes of hydrogen per second.", facts: [{ label: "Radius", value: "696,340 km" }, { label: "Mass", value: "1.99 × 10³⁰ kg" }, { label: "Surface temp", value: "5,772 K" }, { label: "Core temp", value: "15.7 million K" }, { label: "Luminosity", value: "3.83 × 10²⁶ W" }, { label: "Class", value: "G2V" }], palette: ["#c2410c", "#fbbf24", "#fff7d6"] },
  { id: "proxima", name: "Proxima Centauri", type: "star", distance: "4.24 ly", summary: "The nearest star to the Sun, a small flaring red dwarf.", facts: [{ label: "Mass", value: "0.12 M☉" }, { label: "Radius", value: "0.15 R☉" }, { label: "Temp", value: "3,042 K" }, { label: "Class", value: "M5.5Ve" }, { label: "Luminosity", value: "0.0017 L☉" }, { label: "Planets", value: "2–3" }], palette: ["#5a0f0f", "#d1442c", "#ffb38a"] },
  { id: "sirius", name: "Sirius A", type: "star", distance: "8.6 ly", summary: "The brightest star in the night sky, a hot A-type star with a white dwarf companion.", facts: [{ label: "Mass", value: "2.06 M☉" }, { label: "Temp", value: "9,940 K" }, { label: "Class", value: "A0mA1 Va" }, { label: "Luminosity", value: "25.4 L☉" }, { label: "Magnitude", value: "−1.46" }, { label: "Companion", value: "Sirius B (white dwarf)" }], palette: ["#2c4fbf", "#a8c4ff", "#ffffff"] },
  { id: "betelgeuse", name: "Betelgeuse", type: "star", distance: "~550 ly", summary: "A red supergiant in Orion that will one day explode as a supernova.", facts: [{ label: "Radius", value: "~760 R☉" }, { label: "Mass", value: "~16 M☉" }, { label: "Temp", value: "3,600 K" }, { label: "Class", value: "M1-M2 Ia-ab" }, { label: "Age", value: "~10 million yrs" }, { label: "Great Dimming", value: "2019–2020" }], palette: ["#5a1408", "#e0532a", "#ffc08a"] },
  { id: "rigel", name: "Rigel", type: "star", distance: "~860 ly", summary: "A blue supergiant, roughly 120,000 times as luminous as the Sun.", facts: [{ label: "Mass", value: "~21 M☉" }, { label: "Radius", value: "~79 R☉" }, { label: "Temp", value: "12,100 K" }, { label: "Class", value: "B8 Ia" }, { label: "Luminosity", value: "~120,000 L☉" }, { label: "Constellation", value: "Orion" }], palette: ["#1e3aa8", "#7fb0ff", "#eaf3ff"] },
  { id: "vega", name: "Vega", type: "star", distance: "25 ly", summary: "A rapidly rotating A-type star and former pole star; the zero-point of the magnitude scale.", facts: [{ label: "Mass", value: "2.1 M☉" }, { label: "Temp", value: "9,600 K" }, { label: "Rotation", value: "12.5 h" }, { label: "Class", value: "A0Va" }, { label: "Debris disk", value: "Yes" }, { label: "Pole star", value: "~12,000 BCE" }], palette: ["#3355cc", "#b8ccff", "#ffffff"] },
  { id: "milky-way", name: "Milky Way", type: "galaxy", distance: "We live here", summary: "Our home barred spiral galaxy, containing 100–400 billion stars.", facts: [{ label: "Diameter", value: "~100,000 ly" }, { label: "Stars", value: "100–400 billion" }, { label: "Type", value: "SBbc barred spiral" }, { label: "Central BH", value: "Sagittarius A*" }, { label: "Sun's orbit", value: "~230 million yrs" }, { label: "Age", value: "~13.6 billion yrs" }], palette: ["#1b1440", "#7a6fe0", "#f0e6ff"] },
  { id: "andromeda", name: "Andromeda (M31)", type: "galaxy", distance: "2.5 million ly", summary: "The nearest large galaxy, on course to merge with the Milky Way in ~4.5 billion years.", facts: [{ label: "Diameter", value: "~220,000 ly" }, { label: "Stars", value: "~1 trillion" }, { label: "Type", value: "SA(s)b spiral" }, { label: "Approach", value: "110 km/s" }, { label: "Naked eye", value: "Yes" }, { label: "Satellites", value: "M32, M110 +" }], palette: ["#2a1a40", "#a184e0", "#fff0d6"] },
  { id: "triangulum", name: "Triangulum (M33)", type: "galaxy", distance: "2.73 million ly", summary: "The third-largest galaxy in the Local Group, rich in star-forming regions.", facts: [{ label: "Diameter", value: "~60,000 ly" }, { label: "Stars", value: "~40 billion" }, { label: "Type", value: "SA(s)cd" }, { label: "Notable", value: "NGC 604 nebula" }, { label: "Group", value: "Local Group" }, { label: "Magnitude", value: "5.7" }], palette: ["#14204a", "#6e8ae6", "#e4ecff"] },
  { id: "sombrero", name: "Sombrero Galaxy (M104)", type: "galaxy", distance: "~31 million ly", summary: "A striking galaxy with a bright bulge and prominent dust lane, seen nearly edge-on.", facts: [{ label: "Diameter", value: "~50,000 ly" }, { label: "Type", value: "SA(s)a" }, { label: "Central BH", value: "~1 billion M☉" }, { label: "Globular clusters", value: "~2,000" }, { label: "Constellation", value: "Virgo" }, { label: "Magnitude", value: "8.0" }], palette: ["#2a1e10", "#c9a46a", "#fff2d6"] },
  { id: "sgr-a", name: "Sagittarius A*", type: "black hole", distance: "26,670 ly", summary: "The supermassive black hole at the center of the Milky Way, imaged by the EHT in 2022.", facts: [{ label: "Mass", value: "4.15 million M☉" }, { label: "Event horizon", value: "~24 million km" }, { label: "Imaged", value: "2022 (EHT)" }, { label: "Nobel", value: "2020 Physics" }, { label: "S2 star orbit", value: "16 years" }, { label: "Type", value: "Supermassive" }], palette: ["#000000", "#c2410c", "#fbbf24"] },
  { id: "m87", name: "M87*", type: "black hole", distance: "53 million ly", summary: "The first black hole ever imaged, launching a relativistic jet 5,000 light-years long.", facts: [{ label: "Mass", value: "6.5 billion M☉" }, { label: "Imaged", value: "April 2019" }, { label: "Jet length", value: "~5,000 ly" }, { label: "Shadow size", value: "42 μas" }, { label: "Host", value: "Virgo A galaxy" }, { label: "Type", value: "Supermassive" }], palette: ["#000000", "#d9480f", "#ffd8a8"] },
  { id: "cyg-x1", name: "Cygnus X-1", type: "black hole", distance: "7,200 ly", summary: "The first black hole widely accepted, devouring gas from a blue supergiant companion.", facts: [{ label: "Mass", value: "~21 M☉" }, { label: "Companion", value: "HDE 226868" }, { label: "Orbit", value: "5.6 days" }, { label: "Discovered", value: "1964 (X-rays)" }, { label: "Spin", value: "Near maximal" }, { label: "Type", value: "Stellar" }], palette: ["#000000", "#3b5bdb", "#a5d8ff"] },
  { id: "ton-618", name: "TON 618", type: "black hole", distance: "~18 billion ly (comoving)", summary: "One of the most massive black holes known, powering an ultra-luminous quasar.", facts: [{ label: "Mass", value: "~40 billion M☉" }, { label: "Luminosity", value: "~4 × 10⁴⁰ W" }, { label: "Type", value: "Quasar host" }, { label: "Constellation", value: "Canes Venatici" }, { label: "Redshift", value: "2.219" }, { label: "Event horizon", value: "~1,300 AU" }], palette: ["#000000", "#7048e8", "#e5dbff"] },
  { id: "orion-nebula", name: "Orion Nebula (M42)", type: "nebula", distance: "1,344 ly", summary: "The closest massive star-forming region to Earth, visible to the naked eye.", facts: [{ label: "Diameter", value: "~24 ly" }, { label: "Mass", value: "~2,000 M☉" }, { label: "Young stars", value: "~700" }, { label: "Core", value: "Trapezium cluster" }, { label: "Magnitude", value: "4.0" }, { label: "Type", value: "Emission/reflection" }], palette: ["#3a0d3f", "#d6336c", "#74c0fc"] },
  { id: "crab", name: "Crab Nebula (M1)", type: "nebula", distance: "6,500 ly", summary: "The remnant of a supernova seen by astronomers in 1054 CE, with a pulsar at its heart.", facts: [{ label: "Diameter", value: "~11 ly" }, { label: "Pulsar spin", value: "30 times/s" }, { label: "Supernova", value: "1054 CE" }, { label: "Expansion", value: "1,500 km/s" }, { label: "Constellation", value: "Taurus" }, { label: "Type", value: "Supernova remnant" }], palette: ["#2b0d0d", "#e8590c", "#66d9e8"] },
];

export const CATALOG_TYPES: CatalogType[] = ["planet", "star", "moon", "galaxy", "black hole", "nebula"];

export function searchCatalog(query: string, type: CatalogType | "all") {
  const q = query.trim().toLowerCase();
  return CATALOG.filter(
    (e) =>
      (type === "all" || e.type === type) &&
      (!q || e.name.toLowerCase().includes(q) || e.summary.toLowerCase().includes(q) || e.facts.some((f) => f.value.toLowerCase().includes(q))),
  );
}
